services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3308:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  app:
    depends_on: 
      - db
    build: ./src/
    ports:
      - "80:80"
    restart: always
    networks: 
      - dockercompose

networks:
  dockercompose:
volumes:
  db_data: {}